### PR TITLE
Refactor public api and map state

### PR DESCRIPTION
**Pull request by tobrun**
This PR refactors the public api to be invoked directly on `map_view.dart`

```dart
eg
                  mapView.zoom(12.0, 1000.0, 100.0, 5000);
                  // vs
                  mapView.map.zoom(textureId, 12.0, 1000.0, 100.0, 5000);
```

This change also allow to refactor out textureId and adding a getter to the MapState to returning the active texture id at the moment of invoking plugin code. 

cc @tribui @seddonm1

### CODE REVIEW

**Comment by seddonm1** [comment]
if you see the example I added to #18 you can see the public API is already quite clean (separating the issue of using the CameraPosition):

https://github.com/mapbox/flutter-mapbox-gl/pull/18/files#diff-d9a718a3042c2ebab14df5f34ef46a52R41

**Comment by seddonm1** [comment]
I have been looking at the google maps code (WIP):
https://github.com/flutter/plugins/blob/master/packages/google_mobile_maps/example/lib/move_camera.dart

Their code only has examples of invoking map methods (like moveCamera) from within the State component of the widget itself - which is fairly easy. The challenge comes from having a technique for invoking map methods from outside the widget which appears to be either doing something like a Redux or [Streams](https://www.dartlang.org/tutorials/language/streams).

Agree we need to refactor.

**Comment by tobrun** [comment]
@seddonm1 thanks for the handholding while I get familiar with flutter concepts! that said, you are completely right. I'm looking now at migrating to a similar setup as the [video player plugin](https://github.com/flutter/plugins/tree/master/packages/video_player).

**Comment by tobrun** [comment]
@seddonm1 fixed with https://github.com/mapbox/flutter-mapbox-gl/pull/21/commits/eb481628151be1d676bc88b92acc66d7a1ceaf5d, can you review?

**Comment by seddonm1** [comment]
@tobrun sorry but this still doesn't work. try refreshing map (hot-reload) then pressing the button.

Also i think you are slowly drifting back to the original design @tribui - which is actually very similar to the GoogleMaps one - and i believe correct.

I think #18 does all this and i have renamed the components to be `MapboxOverlayController` and `MapboxOverlay` to be aligned with this: https://github.com/flutter/plugins/blob/master/packages/google_mobile_maps/lib/src/controller.dart

Up to you how you want to proceed.

**Comment by tobrun** [comment]
agreed lets move forward with https://github.com/mapbox/flutter-mapbox-gl/pull/18, thank for the work on that!

**Comment by seddonm1** [comment]
cool. if we can get #18 merged i will continue exposing the other api calls

**Pull request closed without merging**
